#!/bin/bash

# ============================================================================
# QUICK START - EAS Build para MyMedication
# ============================================================================
# Referencia rápida de comandos para compilar APK con EAS Build
# ============================================================================

echo "════════════════════════════════════════════════════════════════"
echo "   📱 MyMedication - EAS Build Quick Reference"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "🔧 SETUP INICIAL (ejecutar una sola vez):"
echo "─────────────────────────────────────────"
echo "  # 1. Instalar eas-cli globalmente"
echo "  npm install -g eas-cli@latest"
echo ""
echo "  # 2. Iniciar sesión en Expo"
echo "  eas login"
echo ""
echo "  # 3. Ejecutar script de setup"
echo "  ./setup_eas.sh"
echo ""

echo "🚀 COMPILAR APK (después de setup):"
echo "──────────────────────────────────"
echo "  # Opción A: Usar script automatizado (RECOMENDADO)"
echo "  ./build_eas_apk.sh"
echo ""
echo "  # Opción B: Comando manual"
echo "  eas build --platform android --profile preview"
echo ""

echo "📥 DESCARGAR APK MANUAL:"
echo "───────────────────────"
echo "  # Listar builds"
echo "  eas build:list --platform android"
echo ""
echo "  # Descargar un build específico"
echo "  eas build:download --id=<BUILD_ID> --platform android"
echo ""

echo "📱 INSTALAR EN DISPOSITIVO:"
echo "──────────────────────────"
echo "  # Verificar dispositivo conectado"
echo "  adb devices"
echo ""
echo "  # Instalar APK"
echo "  adb install ./builds/apk/MyMedication-*.apk"
echo ""
echo "  # Desinstalar + Instalar (limpio)"
echo "  adb uninstall com.tunga.mymedication"
echo "  adb install ./builds/apk/MyMedication-*.apk"
echo ""

echo "🔍 MONITOREAR BUILD:"
echo "───────────────────"
echo "  # Ver estado actual"
echo "  eas build:status"
echo ""
echo "  # Ver logs de un build específico"
echo "  eas build:view --id=<BUILD_ID>"
echo ""
echo "  # Abrir en navegador"
echo "  https://expo.dev/builds/<BUILD_ID>"
echo ""

echo "🔐 GESTIÓN DE SESIÓN:"
echo "────────────────────"
echo "  # Ver usuario actual"
echo "  eas whoami"
echo ""
echo "  # Cerrar sesión"
echo "  eas logout"
echo ""
echo "  # Reconfigurar credenciales"
echo "  eas build:configure --platform android --type managed"
echo ""

echo "📋 ARCHIVOS DE CONFIGURACIÓN:"
echo "────────────────────────────"
echo "  eas.json              → Configuración de builds (perfil preview para APK)"
echo "  app.json              → Permisos Android, nombre de app, etc"
echo "  setup_eas.sh          → Setup inicial (run once)"
echo "  build_eas_apk.sh      → Compilar APK (run every build)"
echo "  EAS_BUILD_SETUP.md    → Documentación completa"
echo ""

echo "📚 DOCUMENTACIÓN:"
echo "────────────────"
echo "  Lee EAS_BUILD_SETUP.md para detalles completos"
echo "  Docs oficiales: https://docs.expo.dev/eas-update/getting-started/"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "¿Necesitas ayuda? Consulta EAS_BUILD_SETUP.md"
echo "════════════════════════════════════════════════════════════════"
